<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Forge3D.Core\Forge3D.Core.csproj" />
    <ProjectReference Include="..\Forge3D.Contracts\Forge3D.Contracts.csproj" />
    <ProjectReference Include="..\Forge3D.Simulator\Forge3D.Simulator.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
